name: App CI Pipeline reusable

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  trigger-shared-build:
    uses: rohitkijbile/semtech/.github/workflows/reusable-java-build.yml@master
    with:
      java-version: '17'