name: Reusable Java Build

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'

jobs:
  compile-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Jar Artifact
        run: mvn clean package